<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketExpress.Notificaciones.Aplicacion\MarketExpress.Notificaciones.Aplicacion.csproj" />
    <ProjectReference Include="..\MarketExpress.Notificaciones.Dominio\MarketExpress.Notificaciones.Dominio.csproj" />
  </ItemGroup>

</Project>
